import { EDaysOfWeek } from '@common-enums/days-of-week.enum';
import { EGender } from '@common-enums/gender.enum';
import { EStrokeSide } from '@common-enums/stroke-side.enum';
import {
  pseudoEmail,
  pseudoBirthDate,
} from '@common-utils/anonymization-utils';
import { envConfig } from '@config/environment.config';
import { generateToken } from 'src/misc/generate-token';
import { MigrationInterface, QueryRunner } from 'typeorm';
import {
  Exercise,
  Patient,
  PatientDifficultyData,
  Routine,
  RoutineExecutionData,
  RoutineToExercise,
  User,
} from '../entity';

const demoPatients = [
  {
    name: 'Norman',
    gender: EGender.Male,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 62,
          completion: 55,
          reps: 11,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 58,
          completion: 45,
          reps: 9,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 63,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 66,
          completion: 60,
          reps: 12,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 71,
          completion: 55,
          reps: 11,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 56,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 0,
        },
      ],
    ],
  },
  {
    name: 'Max',
    gender: EGender.DeclineToAnswer,
    mobility: 90,
    performance: 90,
    executionData: [
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
      ],
    ],
  },
  {
    name: 'Laurel',
    gender: EGender.Female,
    mobility: 10,
    performance: 10,
    executionData: [
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 120,
          completion: 50,
          reps: 5,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 120,
          completion: 50,
          reps: 5,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 120,
          completion: 50,
          reps: 5,
          compensation: 0,
          fatigue: 0,
        },
      ],
    ],
  },
  {
    name: 'Charlie',
    gender: EGender.Male,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 50,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 50,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 50,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 50,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 50,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 50,
          fatigue: 0,
        },
      ],
    ],
  },
  {
    name: 'Chloe',
    gender: EGender.Female,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 60,
          completion: 60,
          reps: 12,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 60,
          completion: 40,
          reps: 8,
          compensation: 11,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 75,
          completion: 50,
          reps: 10,
          compensation: 12,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 60,
          completion: 55,
          reps: 11,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 50,
          completion: 45,
          reps: 9,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 60,
          completion: 70,
          reps: 14,
          compensation: 25,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 60,
          completion: 55,
          reps: 11,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 60,
          completion: 45,
          reps: 9,
          compensation: 11,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 12,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 70,
          completion: 60,
          reps: 12,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 65,
          completion: 45,
          reps: 9,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 60,
          completion: 70,
          reps: 14,
          compensation: 25,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 55,
          completion: 75,
          reps: 15,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 75,
          completion: 100,
          reps: 20,
          compensation: 8,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 70,
          reps: 14,
          compensation: 5,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 85,
          completion: 90,
          reps: 18,
          compensation: 6,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 65,
          completion: 85,
          reps: 17,
          compensation: 6,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 55,
          completion: 85,
          reps: 17,
          compensation: 9,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 55,
          completion: 80,
          reps: 16,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 75,
          completion: 100,
          reps: 20,
          compensation: 8,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 70,
          reps: 14,
          compensation: 5,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 85,
          completion: 85,
          reps: 17,
          compensation: 6,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 65,
          completion: 80,
          reps: 16,
          compensation: 13,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 55,
          completion: 85,
          reps: 17,
          compensation: 9,
          fatigue: 0,
        },
      ],
    ],
  },
  {
    name: 'Oscar',
    gender: EGender.Male,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 30,
          completion: 100,
          reps: 20,
          compensation: 0,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 120,
          completion: 50,
          reps: 5,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 120,
          completion: 50,
          reps: 5,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 120,
          completion: 50,
          reps: 5,
          compensation: 0,
          fatigue: 0,
        },
      ],
    ],
  },
  {
    name: 'Felix',
    gender: EGender.Male,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2024-01-03',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 75,
        },
        {
          create_date: '2024-01-03',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 75,
        },
        {
          create_date: '2024-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 75,
        },
        {
          create_date: '2024-01-05',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 75,
        },
        {
          create_date: '2024-01-07',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 75,
        },
        {
          create_date: '2024-01-07',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 75,
        },
      ],
    ],
  },
  {
    name: 'F0',
    gender: EGender.Male,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2024-01-03',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2024-01-03',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2024-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2024-01-05',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2024-01-07',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 0,
        },
        {
          create_date: '2024-01-07',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 0,
        },
      ],
    ],
  },
  {
    name: 'F10',
    gender: EGender.Male,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2024-01-03',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 10,
        },
        {
          create_date: '2024-01-03',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 10,
        },
        {
          create_date: '2024-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 10,
        },
        {
          create_date: '2024-01-05',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 10,
        },
        {
          create_date: '2024-01-07',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 10,
        },
        {
          create_date: '2024-01-07',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 10,
        },
      ],
    ],
  },
  {
    name: 'F25',
    gender: EGender.Male,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2024-01-03',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 25,
        },
        {
          create_date: '2024-01-03',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 25,
        },
        {
          create_date: '2024-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 25,
        },
        {
          create_date: '2024-01-05',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 25,
        },
        {
          create_date: '2024-01-07',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 25,
        },
        {
          create_date: '2024-01-07',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 25,
        },
      ],
    ],
  },
  {
    name: 'F50',
    gender: EGender.Male,
    mobility: 50,
    performance: 50,
    executionData: [
      [
        {
          create_date: '2024-01-03',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 50,
        },
        {
          create_date: '2024-01-03',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 50,
        },
        {
          create_date: '2024-01-05',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 50,
        },
        {
          create_date: '2024-01-05',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 50,
        },
        {
          create_date: '2024-01-07',
          current_set: 1,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 50,
        },
        {
          create_date: '2024-01-07',
          current_set: 2,
          completion_time: 60,
          completion: 50,
          reps: 10,
          compensation: 0,
          fatigue: 50,
        },
      ],
    ],
  },
  {
    name: 'Patient1',
    gender: EGender.Male,
    mobility: 75,
    performance: 60,
    executionData: [
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 110,
          reps: 18,
          completion: 90,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 115,
          reps: 19,
          completion: 95,
          compensation: 8,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 112,
          reps: 17,
          completion: 85,
          compensation: 11,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 113,
          reps: 18,
          completion: 90,
          compensation: 9,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 115,
          reps: 16,
          completion: 80,
          compensation: 12,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 118,
          reps: 17,
          completion: 85,
          compensation: 10,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 105,
          reps: 20,
          completion: 100,
          compensation: 5,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 125,
          reps: 17,
          completion: 85,
          compensation: 12,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 107,
          reps: 19,
          completion: 95,
          compensation: 6,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 123,
          reps: 16,
          completion: 80,
          compensation: 13,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 103,
          reps: 20,
          completion: 100,
          compensation: 4,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 127,
          reps: 15,
          completion: 75,
          compensation: 14,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 115,
          reps: 18,
          completion: 90,
          compensation: 8,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 105,
          reps: 20,
          completion: 100,
          compensation: 7,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 120,
          reps: 16,
          completion: 80,
          compensation: 13,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 108,
          reps: 19,
          completion: 95,
          compensation: 8,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 120,
          reps: 17,
          completion: 85,
          compensation: 11,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 115,
          reps: 16,
          completion: 80,
          compensation: 10,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 120,
          reps: 19,
          completion: 95,
          compensation: 9,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 110,
          reps: 18,
          completion: 90,
          compensation: 6,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 118,
          reps: 16,
          completion: 80,
          compensation: 12,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 110,
          reps: 18,
          completion: 90,
          compensation: 9,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 110,
          reps: 18,
          completion: 90,
          compensation: 8,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 125,
          reps: 15,
          completion: 75,
          compensation: 13,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 125,
          reps: 17,
          completion: 85,
          compensation: 12,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 105,
          reps: 20,
          completion: 100,
          compensation: 5,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 115,
          reps: 17,
          completion: 85,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 120,
          reps: 16,
          completion: 80,
          compensation: 11,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 117,
          reps: 16,
          completion: 80,
          compensation: 12,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 112,
          reps: 18,
          completion: 90,
          compensation: 9,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 110,
          reps: 18,
          completion: 90,
          compensation: 6,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 120,
          reps: 19,
          completion: 95,
          compensation: 8,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 112,
          reps: 18,
          completion: 90,
          compensation: 9,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 118,
          reps: 17,
          completion: 85,
          compensation: 11,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 113,
          reps: 17,
          completion: 85,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 120,
          reps: 16,
          completion: 80,
          compensation: 11,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 115,
          reps: 18,
          completion: 90,
          compensation: 7,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 110,
          reps: 18,
          completion: 90,
          compensation: 7,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 114,
          reps: 17,
          completion: 85,
          compensation: 10,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 111,
          reps: 18,
          completion: 90,
          compensation: 9,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 116,
          reps: 16,
          completion: 80,
          compensation: 11,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 119,
          reps: 17,
          completion: 85,
          compensation: 10,
          fatigue: 0,
        },
      ],
      [
        {
          create_date: '2026-01-03',
          current_set: 1,
          completion_time: 125,
          reps: 17,
          completion: 85,
          compensation: 11,
          fatigue: 0,
        },
        {
          create_date: '2026-01-03',
          current_set: 2,
          completion_time: 105,
          reps: 20,
          completion: 100,
          compensation: 5,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 1,
          completion_time: 119,
          reps: 16,
          completion: 80,
          compensation: 12,
          fatigue: 0,
        },
        {
          create_date: '2026-01-05',
          current_set: 2,
          completion_time: 109,
          reps: 19,
          completion: 95,
          compensation: 8,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 1,
          completion_time: 121,
          reps: 15,
          completion: 75,
          compensation: 13,
          fatigue: 0,
        },
        {
          create_date: '2026-01-07',
          current_set: 2,
          completion_time: 114,
          reps: 17,
          completion: 85,
          compensation: 11,
          fatigue: 0,
        },
      ],
    ],
  },
];
const PREFIXES = ['', '1_', '2_', '3_', '4_', '5_', '6_', '7_', '8_', '9_'];

export class AddDemoInference1655969668916 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const { manager } = queryRunner;

    for (const prefix of PREFIXES) {
      const user = await manager.findOne(User, {
        where: { username: prefix + 'test@test.com' },
      });
      const exercises = await manager.getRepository(Exercise).find();

      const year: number = new Date().getUTCFullYear();
      const month: number = new Date().getUTCMonth();

      const lastMonthDate: Date = new Date();
      lastMonthDate.setDate(0);
      const lastMonth: number = lastMonthDate.getUTCMonth();

      for (const demoPatient of demoPatients) {
        const routine = await manager.getRepository(Routine).save(
          manager.create(Routine, {
            name: `${prefix}${demoPatient.name}'s Routine`,
            therapist: user,
            start_date: '2026-01-03',
            end_date: '2026-01-09',
            repetition_weekdays: [
              EDaysOfWeek.Mon,
              EDaysOfWeek.Wed,
              EDaysOfWeek.Fri,
            ],
          }),
        );
        for (const exercise of exercises) {
          await manager.getRepository(RoutineToExercise).save(
            manager.create(RoutineToExercise, {
              exercise,
              routine,
              time: 120,
              rest_between_sets: 120,
              sets: 2,
              reps: 20,
            }),
          );
        }
        const patient = await manager.getRepository(Patient).save(
          manager.create(Patient, {
            nickname: prefix + demoPatient.name,
            email: prefix + pseudoEmail(),
            access_token: generateToken(envConfig.patientTokenLength),
            therapist: user,
            birth_date: pseudoBirthDate(16, 50),
            gender: demoPatient.gender,
            stroke_side: EStrokeSide.Bilateral,
            routine,
            audit_dates: {
              updated_at: new Date(),
              created_at: new Date(
                Math.random() < 0.5 ? year : year - 1,
                Math.random() < 0.5 ? month : lastMonth,
                15,
              ),
            },
          }),
        );
        await manager.getRepository(PatientDifficultyData).save(
          manager.create(PatientDifficultyData, {
            mobility: demoPatient.mobility,
            performance: demoPatient.performance,
            patient: patient,
          }),
        );

        for (let i = 0; i < exercises.length; i++) {
          const execDataList =
            demoPatient.executionData[i % demoPatient.executionData.length];
          for (const execData of execDataList) {
            const exercise = exercises[i];
            await manager.getRepository(RoutineExecutionData).save(
              manager.create(RoutineExecutionData, {
                patient: patient,
                routine: routine,
                exercise,
                current_set: execData.current_set,
                completion_time: execData.completion_time,
                completion: execData.completion,
                reps: execData.reps,
                compensation: execData.compensation,
                fatigue: execData.fatigue,
                create_date: execData.create_date,
                waypoint_timestamps: [],
              }),
            );
          }
        }
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
