#!/bin/sh
export NVM_DIR="$HOME/.nvm/nvm.sh"
set +e
. "$(dirname $NVM_DIR)/nvm.sh"
set -e

export NVM_DIR="$HOME/.nvm"
a=$(nvm ls | grep 'node')
b=${a#*(-> }
v=${b%%[)| ]*}

export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"

. "$(dirname "$0")/_/husky.sh"

cd sources/backend
npx lint-staged
npm test

cd ../frontend
npx lint-staged
# npm test -- --watch=false --browsers ChromeHeadless